node{
	
	def mvnHome
	def dockerHome
	stage('Checkout'){
	  git url : 'file://E:/Well-Fargo4/workspace/bootapp', branch : 'master'
	  mvnHome = tool 'Local Maven'
	  dockerHome = tool 'MyDocker'
	}
	
	stage('Build'){
		bat(/"${mvnHome}\bin\mvn" clean package/)
	}
	
	stage('Dockerize'){
		bat(/"${dockerHome}\Docker\resources\bin\docker" build -t jenkins-created-image:demo . /)
	}
}